import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Clean Cut Tree - Services in and around Kent',
  description:
    'Clean Cut Tree is a tree surgery company based in Kent, providing professional tree care and maintenance services. We specialize in tree felling, pruning, and stump removal, ensuring the health and safety of your trees. Our experienced team is dedicated to delivering high-quality service with a focus on customer satisfaction.',
  keywords: [
    'tree surgery',
    'Kent',
    'tree care',
    'tree maintenance',
    'tree felling',
    'tree pruning',
    'stump removal',
    'professional tree services',
    'tree health',
    'tree safety',
    'arborist',
    'tree removal',
    'tree trimming',
    'landscaping',
    'garden services',
    'tree management',
    'tree inspection',
    'tree assessment',
    'tree preservation',
    'tree planting',
    'tree care tips',
    'tree service company',
    'Kent tree services',
    'tree care professionals',
    'tree care experts',
    'tree care solutions',
    'tree care specialists',
    'tree care advice',
    'tree care techniques',
    'tree care equipment',
    'tree care products',
    'tree care methods',
    'tree care safety',
    'tree care best practices',
    'tree care maintenance',
    'tree care services',
    'tree surgery kent',
    'kent tree care',
    'tree fellign',
    'tree prunign',
    'stump removl',
    'professioanl tree services',
    'tree helath',
    'tree saefty',
    'arboris',
    'tree removl',
    'tree trimmign',
    'landscapign',
    'garden servcies',
    'tree managemnt',
    'tree inspeciton',
    'tree assesment',
    'tree preservaton',
    'tree plantign',
    'tree care tps',
    'tree service compan',
    'Kent tree servces',
    'tree care profesionals',
    'tree care expets',
    'tree care solutons',
    'tree care specialsts',
    'tree care advce',
    'tree care techniqes',
    'tree care equpment',
    'tree care prducts',
    'tree care methdos',
    'tree care safet',
    'tree care best practces',
    'tree care maintenace',
    'tree care servces',
    'tree surgry',
    'kent tree care',
    'tree fellingg',
    'tree prunin',
    'stump removall',
    'professioanl tree servces',
    'tree helth',
    'tree safty',
    'arboristt',
    'tree removall',
    'tree triming',
    'landscapingg',
    'garden servces',
    'tree managment',
    'tree inspecton',
    'tree assesmentt',
    'tree preservatonn',
    'tree plantin',
    'tree care tipss',
    'tree service companny',
    'Kent tree servces',
    'tree care profesionals',
    'tree care expertss',
    'tree care solutons',
    'tree care specialsts',
    'tree care advicce',
    'tree care techniqes',
    'tree care equpmentt',
    'tree care prducts',
    'tree care methdos',
    'tree care safet',
    'tree care best practces',
    'tree care maintenace',
    'tree care servces',
    'tree surgery kent',
    'kent tree care',
    'tree felling',
    'tree pruning',
    'stump removal',
    'professional tree services',
    'tree health',
    'tree safety',
    'arborist',
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
